input:
  http_server:
    path: /
    ws_path: ""
    sync_response:
      status: ${! meta("status").or(200) }

pipeline:
  processors:
  - try:
    - couchbase:
        server: couchbase://localhost:11210
        username: Administrator
        password: "123456"
        bucket: testing
        timeout: 3s
        operation: "replace"
        key: ${! json("key") }
        value: root = json("value")
  - catch:
    - mapping: |
          root.error = error()
          meta status = if error().contains("key not found")  {
            404
          } else {
            500
          }

output:
  sync_response: {}